Zilon.Core/Zilon.Core/Tactics/Spatial/PathFinding/AStar.cs

#21 change return to empty

---

Zilon.Core/Zilon.Core/Tactics/ISectorEntityManager.cs
Zilon.Core/Zilon.Core/Tactics/SectorEntityManager.cs
Zilon.Core/Zilon.Core/Tactics/Spatial/PathFinding/AStar.cs

#19 Rename parameters

---

Zilon.Core/Zilon.Core.Tests/Tactics/Base/CommonManagerTestsBase.cs
Zilon.Core/Zilon.Core/Tactics/ISectorEntityManager.cs
Zilon.Core/Zilon.Core/Tactics/ManagerItemsChangedEventArgs.cs
Zilon.Core/Zilon.Core/Tactics/Sector.cs
Zilon.Core/Zilon.Core/Tactics/SectorEntityManager.cs
Zilon.Core/Zilon.Core/Tactics/Spatial/PathFinding/AStar.cs
Zilon.Core/Zilon.Core/Zilon.Core.csproj

#18 ManagerItemsChangedArgs

---

Zilon.Core/Zilon.Core.Tests/Persons/Auxiliary/PersonEffectHelperTests.cs
Zilon.Core/Zilon.Core.Tests/Persons/SurvivalDataTests.cs
Zilon.Core/Zilon.Core.Tests/Persons/SurvivalStatTests.cs
Zilon.Core/Zilon.Core.Tests/Tactics/SectorTests.cs
Zilon.Core/Zilon.Core.Tests/Zilon.Core.Tests.csproj
Zilon.Core/Zilon.Core/Persons/SurvivalData.cs
Zilon.Core/Zilon.Core/Persons/SurvivalStat.cs
Zilon.Core/Zilon.Core/Tactics/Spatial/MapBase.cs

Removed the extra member initalizer

Added fix to Issues #20 and #12

---

Zilon.Client/Assets/Zilon/Scripts/Models/Modals/InventorySlotVm.cs
Zilon.Core/Zilon.Core.Tests/Commands/EquipCommandTests.cs
Zilon.Core/Zilon.Core.Tests/Tactics/Spatial/PathFinding/AStarTests.cs
Zilon.Core/Zilon.Core.sln
Zilon.Core/Zilon.Core/Commands/EquipCommand.cs
Zilon.Core/Zilon.Core/Tactics/Behaviour/EquipTask.cs

В рамках этого же PR реализована возможность перекладывать экипировку из одного слота инвентаря в другой. Но на клиенте эта возможность ещё не реализована.

#35 Fix equip

---

Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/SectorVM.cs
Zilon.Core/Zilon.Core/Props/PropStoreEventArgs.cs
Zilon.Core/Zilon.Core/Tactics/ChestBase.cs
Zilon.Core/Zilon.Core/Tactics/DropTableLoot.cs
Zilon.Core/Zilon.Core/Tactics/ILootContainer.cs
Zilon.Core/Zilon.Core/Tactics/IPropContainer.cs
Zilon.Core/Zilon.Core/Tactics/Sector.cs
Zilon.Core/Zilon.Core/Zilon.Core.csproj

Доделано удаление лута при переносе всех предметов в инвентарь. См МР #77

#38 Доделано удаление лута при переносе всех предметов в инвентарь

---

Zilon.Core/Zilon.Core.Tests/Tactics/Behaviour/HumanActorTaskSourceTests.cs
Zilon.Core/Zilon.Core.Tests/Tactics/Behaviour/OpenContainerTaskTests.cs
Zilon.Core/Zilon.Core/Commands/OpenContainerCommand.cs
Zilon.Core/Zilon.Core/Tactics/Behaviour/OpenContainerTask.cs

В рамках этого МР сделана проверка в задаче актёра. Кроме того, добавлена проверка в команде, использующей задачу актёра.

#33 Fix open container on line

---

Zilon.Client/Assets/Zilon/Scenes/combat.unity
Zilon.Client/Assets/Zilon/Scripts/Models/Modals/InventorySlotVm.cs
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/HumanActorGraphicController.cs
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/SectorVM.cs
Zilon.Core/Zilon.Core.Spec/Steps/EquipmentSteps.cs
Zilon.Core/Zilon.Core.Tests/Persons/EquipmentCarrierTests.cs
Zilon.Core/Zilon.Core.Tests/Persons/HumanPersonTests.cs
Zilon.Core/Zilon.Core.Tests/Tactics/Behaviour/EquipTaskTests.cs
Zilon.Core/Zilon.Core/Commands/EquipCommand.cs
Zilon.Core/Zilon.Core/Persons/EquipmentCarrier.cs
Zilon.Core/Zilon.Core/Persons/EquipmentCarrierBase.cs
Zilon.Core/Zilon.Core/Persons/EquipmentCarrierHelper.cs
Zilon.Core/Zilon.Core/Persons/HumanPerson.cs
Zilon.Core/Zilon.Core/Persons/IEquipmentCarrier.cs
Zilon.Core/Zilon.Core/Tactics/Behaviour/AttackTask.cs
Zilon.Core/Zilon.Core/Tactics/Behaviour/EquipTask.cs
Zilon.Core/Zilon.Core/Zilon.Core.csproj

Добавлена возможность снятия экипировки через клик на слот экипировки.
Для решения замечаний из задачи #45

Fix 45 dual weapon unequip

---

Zilon.Core/Zilon.Core.Spec/Steps/EquipmentSteps.cs
Zilon.Core/Zilon.Core.Spec/TestCases/Equipment.feature
Zilon.Core/Zilon.Core.Spec/Zilon.Core.Spec.csproj

Для задачи #45 
Проверены другие типы предметов. Добавлен сценарий спецификации.

Спецификация на снятие экипировки.

---

Zilon.Client/Assets/Zilon/Scripts/Models/Modals/InventoryModalBody.cs

#45 Исправлена возможность деэкипировки

---

Zilon.Client/Assets/Zilon/Prefabs/Sector/EffectViewModel.prefab
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/EffectViewModel.cs
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/PersonEffectHandler.cs

#106 Эффекты отображаются иконками

---

Zilon.Core/Zilon.Core.Benchmark/UnitTest1.cs
Zilon.Core/Zilon.Core.Tests.Common/Schemes/TestTacticalActStatsSubScheme.cs
Zilon.Core/Zilon.Core/Components/TacticalActTargets.cs
Zilon.Core/Zilon.Core/MapGenerators/IChestGeneratorRandomSource.cs
Zilon.Core/Zilon.Core/MapGenerators/MonsterGenerator.cs
Zilon.Core/Zilon.Core/MapGenerators/RoomStyle/RoomGeneratorRandomSource.cs
Zilon.Core/Zilon.Core/Persons/HumanPerson.cs
Zilon.Core/Zilon.Core/Persons/IEquipmentCarrier.cs
Zilon.Core/Zilon.Core/Persons/SurvivalData.cs
Zilon.Core/Zilon.Core/Schemes/ITacticalActStatsSubScheme.cs
Zilon.Core/Zilon.Core/Schemes/TacticalActStatsSubScheme.cs
Zilon.Core/Zilon.Core/Tactics/Behaviour/TaskException.cs
Zilon.Core/Zilon.Core/Tactics/Spatial/HexMap.cs
Zilon.Core/Zilon.Core/Tactics/TacticalActUsageService.cs
Zilon.Core/Zilon.Core/Zilon.Core.csproj

Часть критических замечаний сонара.

#158 sonar

---

Zilon.Client/Assets/Zilon/Scenes/title.unity
Zilon.Client/Assets/Zilon/Scripts/Models/TitleScene/TitleHandler.cs

Добавлена кликабельная ссылка на репу на стартовом экране.

#165 repo url

---

Zilon.Client/Assets/Resources/Schemes/DropTables/default.json
Zilon.Client/Assets/Resources/Schemes/DropTables/survival.json

#170 Исправление дропа стальной брони

#170 Исправление дропа стальной брони

---

Zilon.Client/Assets/Resources/Schemes/Props/Consumables/bottle.json
Zilon.Client/Assets/Resources/Schemes/Props/Consumables/kalin-cheese.json
Zilon.Client/Assets/Resources/Schemes/Props/Consumables/med-kit.json
Zilon.Client/Assets/Resources/Schemes/Props/Consumables/packed-food.json
Zilon.Client/Assets/Resources/Schemes/Props/Consumables/tomaton.json
Zilon.Core/Zilon.Core/Common/PropMetrics.cs
Zilon.Core/Zilon.Core/Tactics/Actor.cs

Для решения #176 
Для всей воды/еды введено правило малого лечения.
Рефакторинг использования предметов.

#176 Для еды/воды добавлено правило малого лечения

---

Zilon.Client/Assets/Zilon/Prefabs/Modals/InventoryModalBody.prefab
Zilon.Client/Assets/Zilon/Prefabs/Modals/PropItem.prefab
Zilon.Client/Assets/Zilon/Scripts/Models/Modals/InventoryModalBody.cs
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/SectorVM.cs

Проблема была в том, что кнопка была видна первоначально. Основная логика работала нормально.
Для решения #184 
Ещё немного улучшено отображение предметов. Сделано в общем стиле. Для задачи #164

Feature 184 improve use button

---

Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/SectorVM.cs

Для решения #181 
Добавлена стартовая экипировка и стартовый провиант

Feature #181 start equips

---

Zilon.Client/Assets/Zilon/Prefabs/Modals/WinModalBody.prefab
Zilon.Client/Assets/Zilon/Prefabs/Modals/WinModalBody.prefab.meta
Zilon.Client/Assets/Zilon/Scenes/combat.unity
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/SectorVM.cs
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/WinModalBody.cs
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/WinModalBody.cs.meta
Zilon.Client/Assets/Zilon/Scripts/Services/SectorModalManager.cs
Zilon.Core/Zilon.Core/Client/ISectorModalManager.cs

В рамках решения задачи #203 был добавлен победный модал.
Модал оформлен как критическая ошибка приложения. После закрытия модала происходит переход на титульный экран.

#203 Добавлен модал победы

---

Zilon.Client/Assets/Zilon/Scripts/GlobalInstaller.cs
Zilon.Client/Assets/Zilon/Scripts/Models/Modals/ActPanelHandler.cs
Zilon.Client/Assets/Zilon/Scripts/Models/Modals/InventoryModalBody.cs
Zilon.Client/Assets/Zilon/Scripts/Models/Modals/PerkItemViewModel.cs
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/MonsterSingleActorGraphicController.cs
Zilon.Client/Assets/Zilon/Scripts/SectorInstaller.cs
Zilon.Client/Assets/Zilon/Scripts/Services/LogService.cs
Zilon.Client/Assets/Zilon/Scripts/Services/SchemeLocator.cs

#244 Убрана лишняя отладочная информация

---

Zilon.Core/Zilon.Core/Commands/AttackCommand.cs
Zilon.Core/Zilon.Core/Persons/HumanPerson.cs
Zilon.Core/Zilon.Core/Tactics/Actor.cs

#158 Исправление оставшихся замечаний по сонару

---

Zilon.Client/Assets/Zilon/Scripts/Models/Modals/InventoryModalBody.cs
Zilon.Client/Assets/Zilon/Scripts/Models/Modals/PropItemVm.cs
Zilon.Client/ProjectSettings/ProjectVersion.txt
Zilon.Core/Zilon.Core/Zilon.Core.csproj

Fix 251 inventory prop selection

---

Zilon.Client/Assets/Resources/VisualProps/Monsters/rat-king.prefab

#250 Исправление визуализации крысиного короля

---

Zilon.Client/Assets/Zilon/Prefabs/Modals/ContainerModalBody.prefab
Zilon.Client/Assets/Zilon/Prefabs/Modals/InventoryModalBody.prefab
Zilon.Client/Assets/Zilon/Prefabs/Modals/PropItem.prefab

Для решения задачи #247 
Размеры остались старыми. Немного увеличен отступ между иконками.

Fix 247 resize prop icons

---

Zilon.Client/Assets/Resources/Schemes/DropTables/survival.json
Zilon.Core/Zilon.Core.Tests/Schemes/SchemeServiceTests.cs
Zilon.Core/Zilon.Core/Schemes/ISchemeService.cs

#146 Исправление схем таблиц дропа

---

Zilon.Client/Assets/Zilon/Scripts/Models/Modals/InventoryModalBody.cs

Для исправления изменений из #263 для задачи #251

#251 Исправление освобождения объектов в модале инвентаря

---

Zilon.Client/Assets/Resources/VisualProps/gold-helmet.prefab
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/SectorVM.cs

Для исправления бага в #188 
Исправил порядок отрисовки для визуализации шлема

#188 Золотой не подлезает под броню

---

Zilon.Client/Assets/Resources/Schemes/DropTables/champion-loot.json
Zilon.Client/Assets/Resources/Schemes/DropTables/default.json

#186 Добавлен дроп патронов для всего стрелкового оружия

---

Zilon.Client/Assets/Zilon/Prefabs/Modals/QuitModalBody.prefab
Zilon.Client/Assets/Zilon/Prefabs/Modals/QuitModalBody.prefab.meta
Zilon.Client/Assets/Zilon/Scenes/combat.unity
Zilon.Client/Assets/Zilon/Scripts/Commands.meta
Zilon.Client/Assets/Zilon/Scripts/Commands/QuitCommand.cs
Zilon.Client/Assets/Zilon/Scripts/Commands/QuitCommand.cs.meta
Zilon.Client/Assets/Zilon/Scripts/Commands/QuitRequestCommand.cs
Zilon.Client/Assets/Zilon/Scripts/Commands/QuitRequestCommand.cs.meta
Zilon.Client/Assets/Zilon/Scripts/GlobalInstaller.cs
Zilon.Client/Assets/Zilon/Scripts/Models/Modals/QuitModalBody.cs
Zilon.Client/Assets/Zilon/Scripts/Models/Modals/QuitModalBody.cs.meta
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/UiHandler.cs
Zilon.Client/Assets/Zilon/Scripts/SectorInstaller.cs
Zilon.Client/Assets/Zilon/Scripts/Services/SectorModalManager.cs
Zilon.Core/Zilon.Core/Client/ISectorModalManager.cs

Для решения #40
Сообщения взял отсюда https://doom.fandom.com/wiki/Quit_messages
И ввёл те, что были в задаче.
На вывод модала и самого выхода сделаны отдельные клиентские команды.

Feature 40 quit request

---

Zilon.Client/Assets/Resources/Schemes/Monsters/manticore.json
Zilon.Client/Assets/Resources/Schemes/Monsters/necromancer.json
Zilon.Client/Assets/Resources/Schemes/Monsters/pit-baron.json
Zilon.Client/Assets/Resources/Schemes/Monsters/skeleton-champion.json
Zilon.Client/Assets/Resources/Schemes/Monsters/skeleton-grunt.json
Zilon.Client/Assets/Resources/Schemes/Monsters/skeleton-warrior.json
Zilon.Client/Assets/Resources/Schemes/Monsters/tests.meta
Zilon.Client/Assets/Resources/Schemes/Monsters/vampire.json
Zilon.Client/Assets/Resources/Schemes/Monsters/zombie.json

Для решения #42 
Дожал все схемы монстров. Дальше остаётся баланс характеристик.

#42 Доделаны схемы монстров

---

Zilon.Client/Assets/Resources/Schemes/Monsters/tests.meta
Zilon.Client/Assets/Zilon/Prefabs/Modals/ScoreModalBody.prefab
Zilon.Client/Assets/Zilon/Scenes/title.unity
Zilon.Client/Assets/Zilon/Scripts/Common.meta
Zilon.Client/Assets/Zilon/Scripts/Common/GameOverEffect.cs
Zilon.Client/Assets/Zilon/Scripts/Common/GameOverEffect.cs.meta
Zilon.Client/Assets/Zilon/Scripts/Models/Modals/ScoreModalBody.cs
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/SectorVM.cs
Zilon.Client/Assets/Zilon/Scripts/Models/TitleScene/TitleHandler.cs
Zilon.Core/Zilon.Core/Tactics/IScoreManager.cs
Zilon.Core/Zilon.Core/Tactics/ScoreManager.cs

Для решения замечаний #42. Решает задачу #285 
Добавлена задержка через отдельный компонент.
Надпись, что игрок мертв в начале детального лога. Пока не вижу, как в текущий модал вставить надпись и иконку (и не ясно, что за иконка, блиц-просмотр не дал результатов).
Исправлено обрезание текста и модал.
При закрытии модала - титульный экран, что по сути означает рестарт игры.

Feature 42 game scores

---

Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/ActorViewModel.cs

Для решения #290
Теперь перемещение выполняется в FixedUpdate. Это сделало анимацию перемещения более стабильной.

#290 Исправлено перемещение в релизе

---

Zilon.Client/Assets/Zilon/Scripts/Models/Modals/InventoryModalBody.cs
Zilon.Client/Assets/Zilon/Scripts/Services/SectorModalManager.cs

Для решения #215
Теперь в модале инвентаря всё завязано на текущего актера из `IPlayerState.ActiveActor`

Work 215 show inventory modal

---

Zilon.Client/Assets/Zilon/Prefabs/Modals/ContainerModalBody.prefab
Zilon.Client/Assets/Zilon/Prefabs/Modals/EquipmentSlot.prefab
Zilon.Client/Assets/Zilon/Prefabs/Modals/InventoryModalBody.prefab
Zilon.Client/Assets/Zilon/Prefabs/Modals/PropInfoPopup.prefab
Zilon.Client/Assets/Zilon/Prefabs/Modals/PropInfoPopup.prefab.meta
Zilon.Client/Assets/Zilon/Prefabs/Modals/PropItem.prefab
Zilon.Client/Assets/Zilon/Scripts/Common/PropInfoPopup.cs
Zilon.Client/Assets/Zilon/Scripts/Common/PropInfoPopup.cs.meta
Zilon.Client/Assets/Zilon/Scripts/Models/IPropViewModelDescription.cs
Zilon.Client/Assets/Zilon/Scripts/Models/IPropViewModelDescription.cs.meta
Zilon.Client/Assets/Zilon/Scripts/Models/Modals/ContainerModalBody.cs
Zilon.Client/Assets/Zilon/Scripts/Models/Modals/InventoryModalBody.cs
Zilon.Client/Assets/Zilon/Scripts/Models/Modals/InventorySlotVm.cs
Zilon.Client/Assets/Zilon/Scripts/Models/Modals/PropItemVm.cs

Для решения #295 
Теперь описание и характеристики предмета выводятся, когда на предмет наведён курсор.

Feature 295 prop info

---

Zilon.Client/Assets/Zilon/Prefabs/Sector/MovePathVisualizer.prefab
Zilon.Client/Assets/Zilon/Prefabs/Sector/MovePathVisualizer.prefab.meta
Zilon.Client/Assets/Zilon/Prefabs/Sector/MovePathVisualizerItem.prefab
Zilon.Client/Assets/Zilon/Prefabs/Sector/MovePathVisualizerItem.prefab.meta
Zilon.Client/Assets/Zilon/Scenes/combat.unity
Zilon.Client/Assets/Zilon/Scripts/Common/PropInfoPopup.cs
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/MapNodeVM.cs
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/MovePathVisualizer.cs
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/MovePathVisualizer.cs.meta
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/SectorVM.cs
Zilon.Core/Zilon.Core/Client/IPlayerState.cs
Zilon.Core/Zilon.Core/Client/PlayerState.cs
Zilon.Core/Zilon.Core/Commands/MoveCommand.cs

Для решения #43 
Иногда при открытии сундука не открывается модал контейнера. Пока не ясно, почему.
Нужно ещё дорабатывать визуализацию. Пока пусть будет так, и будем наблюдать.

Feature 43 move path

---

Zilon.Client/Assets/Zilon/Scenes/title.unity

Для решения #44 
Курсор на титульном экране был не виден.

Fix 44 title cursor

---

Zilon.Client/Assets/Zilon/Scenes/combat.unity
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/ActorHpBar.cs
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/MonsterInfoPanel.cs
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/MonsterInfoPanel.cs.meta

Для решения #50 
Добавлена панель с отображением наименования монстра под курсором и его здоровья в цифрах.

#50 Панель с информацией о монстре

---

Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/ActorGraphicBase.cs
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/ActorViewModel.cs

#85 Исправление атаки трупа

---

Zilon.Client/Assets/Zilon/Prefabs/Modals/PropInfoPopup.prefab
Zilon.Client/Assets/Zilon/Prefabs/Modals/PropItem.prefab
Zilon.Client/Assets/Zilon/Scripts/Common/PropInfoPopup.cs
Zilon.Client/Assets/Zilon/Scripts/GlobalInstaller.cs
Zilon.Client/Assets/Zilon/Scripts/Models/Modals/PropItemVm.cs
Zilon.Client/Assets/Zilon/Scripts/SectorInstaller.cs
Zilon.Core/Zilon.Core.Spec/Mocks/TestEmptySectorGenerator.cs
Zilon.Core/Zilon.Core.Tests/Tactics/SectorTests.cs
Zilon.Core/Zilon.Core.Tests/Tactics/TacticalActUsageServiceTests.cs
Zilon.Core/Zilon.Core/Commands/EquipCommand.cs
Zilon.Core/Zilon.Core/Common/Stat.cs
Zilon.Core/Zilon.Core/MapGenerators/SectorFactory.cs
Zilon.Core/Zilon.Core/Persons/PersonEquipmentHelper.cs
Zilon.Core/Zilon.Core/Persons/SurvivalStat.cs
Zilon.Core/Zilon.Core/Props/Equipment.cs
Zilon.Core/Zilon.Core/Props/EquipmentDurableService.cs
Zilon.Core/Zilon.Core/Props/EquipmentDurableServiceRandomSource.cs
Zilon.Core/Zilon.Core/Props/IEquipmentDurableService.cs
Zilon.Core/Zilon.Core/Props/IEquipmentDurableServiceRandomSource.cs
Zilon.Core/Zilon.Core/Tactics/Behaviour/EquipTask.cs
Zilon.Core/Zilon.Core/Tactics/ITacticalActUsageRandomSource.cs
Zilon.Core/Zilon.Core/Tactics/Sector.cs
Zilon.Core/Zilon.Core/Tactics/TacticalActUsageRandomSource.cs
Zilon.Core/Zilon.Core/Tactics/TacticalActUsageService.cs
Zilon.Core/Zilon.Core/Zilon.Core.csproj

Для решения #132 
Частичное решение. Сейчас есть только износ. Ремонт будет сделан в следующем МР.

#132 Износ экипировки

---

Zilon.Client/Assets/Zilon/Scenes/combat.unity
Zilon.Core/Zilon.Core/Persons/EquipmentCarrier.cs
Zilon.Core/Zilon.Core/Persons/EquipmentCarrierBase.cs
Zilon.Core/Zilon.Core/Persons/IEquipmentCarrier.cs

#209 Обобщение EquipmentCarrier

---

Zilon.Core/Zilon.Core.Spec/Steps/SurvivalSteps.cs
Zilon.Core/Zilon.Core.Spec/TestCases/Survival.feature
Zilon.Core/Zilon.Core/Persons/HumanSurvivalData.cs
Zilon.Core/Zilon.Core/Persons/ISurvivalDataExtensions.cs
Zilon.Core/Zilon.Core/Persons/SurvivalStatKeyPoint.cs
Zilon.Core/Zilon.Core/Zilon.Core.csproj

Для решения #216 
Явную установку эффекта в спеках оставил, чтобы не завязываться на значения и держать спеку проще.
Вместо этого введен промежуточный метод для получения эффектов при форсированном изменении  значения.

Refactor 216 useself equip

---

Zilon.Core/Zilon.Core.Tests/Persons/SurvivalDataTests.cs
Zilon.Core/Zilon.Core/Persons/HumanSurvivalData.cs

Для решения #230 
Добавлен конструктор с указанием стартовых характеристик

#230 Конструктор HumanSurvivalData с указанием характеристик

---

Zilon.Client/Assets/Zilon/Scripts/Models/GlobeScene/GlobeWorldVM.cs
Zilon.Core/Zilon.Core/Commands/CommandCantExecuteException.cs
Zilon.Core/Zilon.Core/Commands/Globe/MoveGroupCommand.cs
Zilon.Core/Zilon.Core/Zilon.Core.csproj

Всё сделано просто (по-тупому). Команда не может выполняться, если есть угроза выживания.

#331 Запрет путешествий при критическом уровне голода/жажды

---

Zilon.Core/Zilon.Core/Commands/Globe/MoveGroupCommand.cs

Feature 328 survival hazard on globe

---

Zilon.Client/Assets/Zilon/Scripts/Models/GlobeScene/GlobeWorldVM.cs
Zilon.Core/Zilon.Core/CommonServices/Dices/IDiceExtensions.cs
Zilon.Core/Zilon.Core/MapGenerators/IMonsterGenerator.cs
Zilon.Core/Zilon.Core/MapGenerators/MonsterGenerator.cs
Zilon.Core/Zilon.Core/MapGenerators/SectorGenerator.cs
Zilon.Core/Zilon.Core/World/GlobeRegion.cs
Zilon.Core/Zilon.Core/World/GlobeRegionNode.cs
Zilon.Core/Zilon.Core/World/GlobeRegionNodeMonsterState.cs
Zilon.Core/Zilon.Core/World/IWorldManager.cs
Zilon.Core/Zilon.Core/World/MonsterSet.cs
Zilon.Core/Zilon.Core/World/WildMeetingEventArgs.cs
Zilon.Core/Zilon.Core/World/WorldManager.cs
Zilon.Core/Zilon.Core/Zilon.Core.csproj

Теперь есть случайные встречи во время путешествий.
Осталось продумать, как чистить мертвых персонажей.

Промежуточный МР #332 wild meetings

---

Zilon.Client/Assets/Zilon/Scripts/Models/GlobeScene/GlobeWorldVM.cs
Zilon.Client/Assets/Zilon/Scripts/Models/GlobeScene/MapLocation.cs
Zilon.Client/Assets/Zilon/Scripts/Models/GlobeScene/MapLocationConnector.cs
Zilon.Client/ProjectSettings/ProjectVersion.txt
Zilon.Core/Tests.md
Zilon.Core/Zilon.Core.sln
Zilon.Core/Zilon.Core/Commands/Globe/MoveGroupCommand.cs
Zilon.Core/Zilon.Core/World/GlobeNodeObservedState.cs
Zilon.Core/Zilon.Core/World/GlobeRegionNode.cs
Zilon.Core/Zilon.Core/Zilon.Core.csproj

#351
Сейчас не показываются узлы для перехода между провинциями. Будет сделано в отдельно задаче.

Feature 351 only observed nodes on globe

---

Zilon.Client/Assets/Zilon/Scenes/globe.unity
Zilon.Client/Assets/Zilon/Scripts/Commands/QuitRequestCommand.cs
Zilon.Client/Assets/Zilon/Scripts/Common/GameOverEffect.cs
Zilon.Client/Assets/Zilon/Scripts/GlobalFollowCamera.cs
Zilon.Client/Assets/Zilon/Scripts/GlobeInstaller.cs
Zilon.Client/Assets/Zilon/Scripts/Models/GlobeScene/GlobeWorldVM.cs
Zilon.Client/Assets/Zilon/Scripts/Models/GlobeScene/MapLocation.cs
Zilon.Client/Assets/Zilon/Scripts/Models/Modals/ScoreModalBody.cs
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/MonsterSingleActorGraphicController.cs
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/SectorVM.cs
Zilon.Client/Assets/Zilon/Scripts/SectorInstaller.cs
Zilon.Client/Assets/Zilon/Scripts/Services/GlobeModalManager.cs
Zilon.Client/Assets/Zilon/Scripts/Services/GlobeModalManager.cs.meta
Zilon.Core/Zilon.Core/Client/Windows/ICommonModalManager.cs
Zilon.Core/Zilon.Core/Client/Windows/IGlobeModalManager.cs
Zilon.Core/Zilon.Core/Client/Windows/ISectorModalManager.cs
Zilon.Core/Zilon.Core/Commands/Sector/ShowContainerModalCommand.cs
Zilon.Core/Zilon.Core/Commands/Sector/ShowInventoryModalCommand.cs
Zilon.Core/Zilon.Core/Commands/Sector/ShowModalCommandBase.cs
Zilon.Core/Zilon.Core/Commands/Sector/ShowPerksModalCommand.cs
Zilon.Core/Zilon.Core/Commands/Sector/ShowTraderModalCommand.cs
Zilon.Core/Zilon.Core/Tactics/IScoreManager.cs
Zilon.Core/Zilon.Core/Tactics/ScoreAchievements.cs
Zilon.Core/Zilon.Core/Tactics/ScoreManager.cs
Zilon.Core/Zilon.Core/World/GlobeRegionNode.cs
Zilon.Core/Zilon.Core/WorldGeneration/WorldGenerator.cs
Zilon.Core/Zilon.Core/Zilon.Core.csproj

Первая итерация. Победный узел в той же провинции, что и группа игрока

---

Zilon.Client/Assets/Zilon/Scripts/Models/GlobeScene/GlobeWorldVM.cs
Zilon.Core/Zilon.Core/Common/HexHelper.cs
Zilon.Core/Zilon.Core/OffsetCoordsExtensions.cs
Zilon.Core/Zilon.Core/WorldGeneration/AgentCards/CreateLocality.cs
Zilon.Core/Zilon.Core/WorldGeneration/DirectBitmap.cs
Zilon.Core/Zilon.Core/WorldGeneration/Globe.cs
Zilon.Core/Zilon.Core/WorldGeneration/ScanResult.cs
Zilon.Core/Zilon.Core/WorldGeneration/WorldGenerator.cs
Zilon.Core/Zilon.Core/Zilon.Core.csproj

#327
Нужно сделать индикатор, насколько игрок приблизился к цели.
Варианты решения:
1. Запоминать последнюю посещенную провинцию. При перемещении между провинциями на глобальной карте выводить сообщение "горячо-холодно". Выглядит заманчивым, особенно для выставки. Но не очень хорошо применимо в рамках дальнейшего развития проекта. Потому что предполагается, что поиск дома будет занимать второй акт из трёх. То есть 66% времени этот функционал будет не нужен.
2. Запилить первоначальные квесты. Первый и единственный квест - найти дом. При входе в любой населённый пункт у прохожих, если квест активен, можно будет спрашивать, где находится город, который выбран как целевой. А они будут говорить, куда двигаться. Например, "Это нужно на восток, в город такой-то, оттуда на север. А там спросить." …

Feature 327 home node

---

Zilon.Core/Zilon.Core/WorldGeneration/GlobeRegionPatterns.cs
Zilon.Core/Zilon.Core/WorldGeneration/WorldGenerator.cs

#354 Гарантированная генерация города и данжа рядом с игроком

---

Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/CombatLogPanel.cs

#352 Все логи зачищаются, когда текст перестаёт быть виден

---

Zilon.Client/Assets/Resources/Schemes/Perks/death-feeling.json
Zilon.Client/Assets/Resources/Schemes/Perks/death-feeling.json.meta
Zilon.Client/Assets/Resources/Schemes/Perks/vitality.json
Zilon.Client/Assets/Resources/Schemes/Perks/vitality.json.meta
Zilon.Client/Assets/Resources/Schemes/Perks/white-scars.json
Zilon.Client/Assets/Resources/Schemes/Perks/white-scars.json.meta
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/SectorVM.cs
Zilon.Core/Zilon.BotEnvironment/Program.cs
Zilon.Core/Zilon.Core.Spec/Contexts/FeatureContextBase.cs
Zilon.Core/Zilon.Core.Tests/Persons/HumanPersonTests.cs
Zilon.Core/Zilon.Core/Components/PersonRuleType.cs
Zilon.Core/Zilon.Core/Persons/ConsumeProviantJobProgress.cs
Zilon.Core/Zilon.Core/Persons/HumanPerson.cs
Zilon.Core/Zilon.Core/Persons/SurvivalStatBonus.cs
Zilon.Core/Zilon.Core/Persons/TakeDamageJobProgress.cs
Zilon.Core/Zilon.Core/Persons/TakeHitJobProgress.cs
Zilon.Core/Zilon.Core/Schemes/JobType.cs
Zilon.Core/Zilon.Core/Tactics/Actor.cs
Zilon.Core/Zilon.Core/Zilon.Core.csproj

Добавлен перк на увеличение ХП

---

Zilon.Client/Assets/Resources/Schemes/Props/Equipments/anger-axe.json
Zilon.Client/Assets/Resources/Schemes/Props/Equipments/battle-axe.json
Zilon.Client/Assets/Resources/Schemes/Props/Equipments/bow.json
Zilon.Client/Assets/Resources/Schemes/Props/Equipments/composite-bow.json
Zilon.Client/Assets/Resources/Schemes/Props/Equipments/fireball-staff.json
Zilon.Client/Assets/Resources/Schemes/Props/Equipments/flail.json
Zilon.Client/Assets/Resources/Schemes/Props/Equipments/heal-staff.json
Zilon.Client/Assets/Resources/Schemes/Props/Equipments/knobstick.json
Zilon.Client/Assets/Resources/Schemes/Props/Equipments/mace.json
Zilon.Client/Assets/Resources/Schemes/Props/Equipments/pistol.json
Zilon.Client/Assets/Resources/Schemes/Props/Equipments/rush-sword.json
Zilon.Client/Assets/Resources/Schemes/Props/Equipments/shadow-staff.json
Zilon.Client/Assets/Resources/Schemes/Props/Equipments/short-sword.json
Zilon.Client/Assets/Resources/Schemes/Props/Equipments/suprime-anger-axe.json
Zilon.Client/Assets/Resources/Schemes/Props/Equipments/tribal-spear.json
Zilon.Client/Assets/Zilon/Prefabs/Modals/PropInfoPopup.prefab
Zilon.Client/Assets/Zilon/Scripts/Common/PropInfoPopup.cs

#342 Теги для оружия

---

Zilon.Core/Zilon.Core/Common/ListHelper.cs
Zilon.Core/Zilon.Core/WorldGeneration/AgentCards/TransportHelper.cs
Zilon.Core/Zilon.Core/Zilon.Core.csproj

Refactor 393 article

---

Zilon.Client/Assets/Zilon/Prefabs/Sector/DodgeIndicator.prefab
Zilon.Client/Assets/Zilon/Prefabs/Sector/DodgeIndicator.prefab.meta
Zilon.Client/Assets/Zilon/Prefabs/Sector/PureMissIndicator.prefab
Zilon.Client/Assets/Zilon/Prefabs/Sector/PureMissIndicator.prefab.meta
Zilon.Client/Assets/Zilon/Scenes/combat.unity
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/AttackIndicatorBase.cs
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/AttackIndicatorBase.cs.meta
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/DodgeIndicator.cs
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/DodgeIndicator.cs.meta
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/PureMissIndicator.cs
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/PureMissIndicator.cs.meta
Zilon.Client/Assets/Zilon/Scripts/Services/SceneDirector.cs

#127 Индикаторы промаха и уклонения

---

Zilon.Client/Assets/Zilon/Prefabs/Sector/BlockIndicator.prefab
Zilon.Client/Assets/Zilon/Prefabs/Sector/BlockIndicator.prefab.meta
Zilon.Client/Assets/Zilon/Prefabs/Sector/BlockSparks.prefab
Zilon.Client/Assets/Zilon/Prefabs/Sector/BlockSparks.prefab.meta
Zilon.Client/Assets/Zilon/Scenes/combat.unity
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/BlockIndicator.cs
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/BlockIndicator.cs.meta
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/BlockSparks.cs
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/BlockSparks.cs.meta
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/DodgeIndicator.cs
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/NoDamageIndicatorBase.cs
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/NoDamageIndicatorBase.cs.meta
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/PureMissIndicator.cs
Zilon.Client/Assets/Zilon/Scripts/Services/SceneDirector.cs

#125 Визуализация блока

---

Zilon.Client/Assets/Zilon/Scripts/Common/HpBar.cs
Zilon.Client/Assets/Zilon/Scripts/Common/HpBarHighlighter.cs
Zilon.Client/Assets/Zilon/Scripts/Common/HpBarHighlighter.cs.meta

#408 Миграние ХП-бара при получении урона

---

Zilon.Client/Assets/Zilon/Scenes/combat.unity

#408 Сохранение сцены

---

Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/BloodTracker.cs
Zilon.Client/Assets/Zilon/Scripts/Services/SceneDirector.cs

#126 Исправление рандомизации пятен крови

---

Zilon.Client/Assets/Zilon/Scenes/combat.unity
Zilon.Client/Assets/Zilon/Scripts/Common/HpBar.cs
Zilon.Client/Assets/Zilon/Scripts/Common/HpBarHighlighter.cs
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/NoBulletHandler.cs
Zilon.Client/Assets/Zilon/Sprites/health-bar-portfolio.png.meta

#408 Перенос шкалы ХП

---

Zilon.Client/Assets/Zilon/Prefabs/Common/EffectViewModel.prefab
Zilon.Client/Assets/Zilon/Scenes/combat.unity
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/EffectViewModel.cs

#411 Название эффекта угрозы выживания

---

Zilon.Client/Assets/Zilon/Prefabs/Sector/Chest.prefab
Zilon.Client/Assets/Zilon/Prefabs/Sector/ContainerBase.prefab
Zilon.Client/Assets/Zilon/Prefabs/Sector/Loot.prefab
Zilon.Client/Assets/Zilon/Prefabs/Sector/trash.prefab
Zilon.Client/Assets/Zilon/Sprites/Props/sprite_413.png.meta
Zilon.Client/Assets/Zilon/Sprites/Props/sprite_414.png.meta

#297 #440 Коллайдеры и размеры сундуков

---

Zilon.Client/Assets/Zilon/Prefabs/Modals/DialogModalBody.prefab
Zilon.Client/Assets/Zilon/Prefabs/Modals/ScoreModalBody.prefab
Zilon.Client/Assets/Zilon/Sounds/main dungeon theme.mp3.meta

#412 Исправление модалов диалога и результатов игры

---

Zilon.Client/Assets/Zilon/Prefabs/Modals/EquipmentSlot.prefab
Zilon.Client/Assets/Zilon/Prefabs/Modals/InventoryModalBody.prefab
Zilon.Client/Assets/Zilon/Prefabs/Modals/PropItem.prefab
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/InventoryHandler.cs
Zilon.Client/ProjectSettings/GraphicsSettings.asset

#413 Исправление проблем с выбором предмета в панели инвентаря

---

Zilon.Core/Zilon.Core.MassSectorGenerator/App.config
Zilon.Core/Zilon.Core.MassSectorGenerator/Program.cs
Zilon.Core/Zilon.Core.MassSectorGenerator/Properties/AssemblyInfo.cs
Zilon.Core/Zilon.Core.MassSectorGenerator/Startup.cs
Zilon.Core/Zilon.Core.MassSectorGenerator/Zilon.Core.MassSectorGenerator.csproj
Zilon.Core/Zilon.Core.MassSectorGenerator/packages.config
Zilon.Core/Zilon.Core.Tests/MapGenerators/MonsterGeneratorTests.cs
Zilon.Core/Zilon.Core.sln
Zilon.Core/Zilon.Core/MapGenerators/ChestGenerator.cs
Zilon.Core/Zilon.Core/MapGenerators/MonsterGenerator.cs
Zilon.Core/Zilon.Core/MapGenerators/SectorGenerator.cs
Zilon.Core/Zilon.Core/Tactics/Spatial/GraphMap.cs
Zilon.Core/Zilon.Core/Tactics/Spatial/HexMap.cs
Zilon.Core/Zilon.Core/Tactics/Spatial/HexNode.cs
Zilon.Core/Zilon.Core/Tactics/Spatial/IMap.cs
Zilon.Core/Zilon.Core/Tactics/Spatial/MapBase.cs

#439
В рамках этой же задачи исправлена проблема, когда монстры генерируются на ящик.

#439 Исправление наложения контейнеров на препятствия

---

Zilon.Client/Assets/Zilon/Scripts/Models/Modals/ModalDialog.cs
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/SectorUiHandler.cs
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/SectorVM.cs

#409 Хоткеи на интерфейс

---

Zilon.Client/Assets/Zilon/Prefabs/Sector/Loot.prefab
Zilon.Client/Assets/Zilon/Prefabs/Sector/trash.prefab
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/ContainerVm.cs

#439 Исправление коллайдеров контейнеров

---

Zilon.Client/Assets/Zilon/Scripts/Commands/KeyboardMoveController.cs
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/SectorUiHandler.cs

#271 Доработки перемещения с клавиатуры

---

Zilon.Client/Assets/Zilon/Scenes/combat.unity
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/InventoryHandler.cs

#413 Исправление панели инвентаря

---

Zilon.Client/Assets/Zilon/Scripts/Models/GlobeScene/GlobeWorldVM.cs
Zilon.Core/Zilon.Core.Tests/World/GlobeHelperTestCaseSource.cs
Zilon.Core/Zilon.Core.Tests/World/GlobeHelperTests.cs
Zilon.Core/Zilon.Core.Tests/Zilon.Core.Tests.csproj
Zilon.Core/Zilon.Core/World/GlobeHelper.cs
Zilon.Core/Zilon.Core/Zilon.Core.csproj

#457 Исправление подложки на глобальной карте

---

Zilon.Client/Assets/Zilon/Scenes/combat.unity
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/SectorUiHandler.cs
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/SectorVM.cs
Zilon.Client/Assets/Zilon/Scripts/SectorInstaller.cs
Zilon.Core/Zilon.Core/Commands/Sector/ActorCommandBase.cs
Zilon.Core/Zilon.Core/Commands/Sector/SectorTransitionMoveCommand.cs
Zilon.Core/Zilon.Core/Tactics/ISector.cs
Zilon.Core/Zilon.Core/Tactics/Sector.cs
Zilon.Core/Zilon.Core/Zilon.Core.csproj

#450 Перемещение между секторами через кнопку

---

Zilon.Client/Assets/Zilon/Prefabs/Sector/Hex.prefab
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/ActorGraphicBase.cs
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/SectorVM.cs

#465 Исправление порядка отрисовки объектов в секторе

---

Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/MonsterInfoPanel.cs

#462 Не выводить информацию о монстре в городах

---

Zilon.Core/Zilon.Core.MassSectorGenerator/Program.cs

#217 #309 Корректность генерации объектов в секторе

---

Zilon.Client/Assets/Resources/Schemes/Locations/rat-kingdom.json
Zilon.Core/Zilon.Core.MassSectorGenerator/Program.cs

#473 Исправление опечатки + проверка переходов

---

Zilon.Client/Assets/Zilon/Scenes/scores.unity
Zilon.Client/Assets/Zilon/Scripts/Models/Scores/ScoresHandler.cs

#359 Исправление окна с таблицей рекордов

---

Zilon.Client/Assets/Zilon/Prefabs/Modals/EquipmentSlot.prefab
Zilon.Client/Assets/Zilon/Scenes/combat.unity
Zilon.Client/Assets/Zilon/Scripts/Models/Modals/DoubleClickPropHandler.cs
Zilon.Client/Assets/Zilon/Scripts/Models/Modals/DraggedPropItem.cs
Zilon.Client/Assets/Zilon/Scripts/Models/Modals/InventoryDropHandler.cs
Zilon.Client/Assets/Zilon/Scripts/Models/Modals/InventoryDropHandler.cs.meta
Zilon.Client/Assets/Zilon/Scripts/Models/Modals/InventorySlotDragHandler.cs
Zilon.Client/Assets/Zilon/Scripts/Models/Modals/InventorySlotDragHandler.cs.meta
Zilon.Client/Assets/Zilon/Scripts/Models/Modals/InventorySlotDropHandler.cs
Zilon.Client/Assets/Zilon/Scripts/Models/Modals/InventorySlotDropHandler.cs.meta
Zilon.Client/Assets/Zilon/Scripts/Models/Modals/InventorySlotVm.cs
Zilon.Client/Assets/Zilon/Scripts/Models/Modals/PropDragHandler.cs
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/InventoryHandler.cs
Zilon.Client/Assets/Zilon/Scripts/SectorInstaller.cs
Zilon.Client/Assets/Zilon/Scripts/Services/SpecialCommandManager.cs
Zilon.Client/Assets/Zilon/Scripts/Services/SpecialCommandManager.cs.meta

#117 Упрощённая экипировка предметов

---

Zilon.Client/Assets/Zilon/Prefabs/Modals/EquipmentSlot.prefab
Zilon.Client/Assets/Zilon/Prefabs/Modals/InventoryPropItem.prefab
Zilon.Client/Assets/Zilon/Scenes/combat.unity

#117 Удаление лишних Event Trigger компонентов

---

Zilon.Client/Assets/Zilon/Scenes/combat.unity
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/SectorUiHandler.cs

#484 Быстрое решение для выхода из города

---

Zilon.Client/Assets/Editor.meta
Zilon.Client/Assets/Editor/AutoSaveOnRunMenuItem.cs
Zilon.Client/Assets/Editor/AutoSaveOnRunMenuItem.cs.meta
Zilon.Client/Assets/Zilon/Scenes/combat.unity

#484
Так же добавил скрипт, который автоматически сохраняет сцену. Автосохранение включается через меню Tools.

#484 Забытое сохранение сцены

---

Zilon.Core/Zilon.Core/Commands/Sector/AttackCommand.cs
Zilon.Core/Zilon.Core/Commands/Sector/MoveCommand.cs

#482
Задача пока заморожена. Результат рефакторинга можно слить в мастер, чтобы не потерялся.

#482 Рефакторинг

---

Zilon.Core/Zilon.Core/Tactics/Actor.cs

#506 Исправление употребления эля северян

---

Zilon.Client/Assets/Zilon/Scenes/combat.unity
Zilon.Client/Assets/Zilon/Scripts/Common/TooltipManager.cs
Zilon.Client/Assets/Zilon/Scripts/Common/TooltipManager.cs.meta
Zilon.Client/Assets/Zilon/Scripts/Common/UiElementTooltip.cs
Zilon.Client/Assets/Zilon/Scripts/Common/UiElementTooltip.cs.meta

#510 Тултипы на элементы интерфейса

---

.circleci/config.yml
README.md
Zilon.Core/Zilon.Bot.Players/Triggers/HasBetterEquipmentTrigger.cs
Zilon.Core/Zilon.BotEnvironment/Program.cs
Zilon.Core/Zilon.Core/Scoring/DetailedLifetime.cs
Zilon.Core/Zilon.Core/Scoring/ScoreCalculator.cs
Zilon.Core/Zilon.Core/Scoring/TextSummaryHelper.cs
Zilon.Core/Zilon.Core/WorldGeneration/AgentCards/TakeLocation.cs
Zilon.Core/Zilon.Core/Zilon.Core.csproj

#528 
Это МР в первую очередь для проверки работы LGTM.

#528 Исправление замечаний от lgtm

---

Zilon.Client/Assets/Zilon/Scenes/combat.unity
Zilon.Client/Assets/Zilon/Scripts/Commands/QuitTitleCommand.cs
Zilon.Client/Assets/Zilon/Scripts/Commands/QuitTitleCommand.cs.meta
Zilon.Client/Assets/Zilon/Scripts/Commands/QuitTitleRequestCommand.cs
Zilon.Client/Assets/Zilon/Scripts/Commands/QuitTitleRequestCommand.cs.meta
Zilon.Client/Assets/Zilon/Scripts/GlobalInstaller.cs
Zilon.Client/Assets/Zilon/Scripts/Models/Modals/QuitModalBody.cs
Zilon.Client/Assets/Zilon/Scripts/Services/CommonModalManagerBase.cs
Zilon.Client/Assets/Zilon/Scripts/Services/CommonModalManagerBase.cs.meta
Zilon.Client/Assets/Zilon/Scripts/Services/GlobeModalManager.cs
Zilon.Client/Assets/Zilon/Scripts/Services/ModalManagerBase.cs
Zilon.Client/Assets/Zilon/Scripts/Services/ModalManagerBase.cs.meta
Zilon.Client/Assets/Zilon/Scripts/Services/SectorModalManager.cs
Zilon.Core/Zilon.Core/Client/Windows/ICommonModalManager.cs
Zilon.Core/Zilon.Core/Scoring/TextSummaryHelper.cs

Добавлена кнопка выхода в меню

---

Zilon.Core/Zilon.Core/Tactics/Behaviour/Bots/IBotLogic.cs
Zilon.Core/Zilon.Core/Tactics/Behaviour/Bots/IDecisionSource.cs
Zilon.Core/Zilon.Core/Tactics/Behaviour/Bots/PatrolRoute.cs
Zilon.Core/Zilon.Core/Zilon.Core.csproj

#325
Источник команд для монстров уже упразднён.
В ветке выполнена чистка и документирование.

#325 Рефакторинг, чистка, документирование

---

.circleci/config.yml
Zilon.Core/Zilon.Core/WorldGeneration/WorldGenerator.cs

Откат тестовых изменений

---

Zilon.Core/Zilon.Core/WorldGeneration/NameGeneration/NameGen.cs

Для NameGen добавить перегрузки конструкторов

---

Zilon.Client/Assets/Zilon/Scripts/Models/Modals/DraggedPropItem.cs
Zilon.Client/Assets/Zilon/Scripts/Models/Modals/PropItemViewModelBase.cs
Zilon.Client/Assets/Zilon/Scripts/Models/Modals/PropItemVm.cs

#554 Удаление дубликатов

---

Zilon.Client/Assets/Zilon/Scripts/GlobalInstaller.cs
Zilon.Client/Assets/Zilon/Scripts/Models/Modals/ContainerModalBody.cs
Zilon.Client/Assets/Zilon/Scripts/Models/Modals/ContainerModalBodyBase.cs
Zilon.Client/Assets/Zilon/Scripts/Models/Modals/ContainerModalBodyBase.cs.meta
Zilon.Client/Assets/Zilon/Scripts/Models/Modals/ContainerPopup.cs
Zilon.Client/Assets/Zilon/Scripts/Models/Modals/PropItemViewModelBase.cs.meta

#553 Замечания Better Code Hub

---

Zilon.Core/Zilon.Core.Tests/Tactics/DropResolverTests.cs
Zilon.Core/Zilon.Core/Tactics/DropResolver.cs

#556 Уменьшен дроп злых тыкв

---

Zilon.Core/Zilon.Core.Tests/Tactics/ActorTests.cs
Zilon.Core/Zilon.Core/Tactics/Actor.cs

#573 Исправление ошибки снижения интоксикации

---

Zilon.Core/Zilon.Core/Persons/BaseSurvivalData.cs
Zilon.Core/Zilon.Core/Persons/HumanSurvivalData.cs
Zilon.Core/Zilon.Core/Persons/MonsterSurvivalData.cs
Zilon.Core/Zilon.Core/Persons/SurvivalDataBase.cs
Zilon.Core/Zilon.Core/Zilon.Core.csproj

Refactor code for issue #560

---

.circleci/config.yml
Zilon.Core/Zilon.Core.Spec/packages.config
Zilon.Core/Zilon.Core.Tests/packages.config

#527 Покрытие кода тестами в Codacy

---

Zilon.Core/Zilon.Core.Tests/MapGenerators/CellularAutomatonStyle/InteriorObjectRandomSourceTests.cs
Zilon.Core/Zilon.Core.Tests/Zilon.Core.Tests.csproj
Zilon.Core/Zilon.Core/MapGenerators/CellularAutomatonStyle/CellularAutomatonMapFactory.cs
Zilon.Core/Zilon.Core/MapGenerators/CellularAutomatonStyle/InteriorObjectRandomSource.cs

#575 исправление ошибки при генерации пещер CA

---

Zilon.Client/Assets/Resources/Schemes/TacticalActs/mimics/slash-mimic.json
Zilon.Client/Assets/Resources/Schemes/TacticalActs/mimics/slash-mimic.json.meta

#557 Добавлено забытое лже-действие

---

Zilon.Core/Zilon.Core.Tests/Schemes/SchemeServiceTests.cs

#577 Добавлен тест для проверки согласованности схем

---

.circleci/config.yml

#527 Исправление отправки покрытия на сервер Codacy

---

.circleci/config.yml

#527 Сбор покрытия после выполнения тестов

---

Zilon.Client/Assets/Zilon/Scenes/combat.unity
Zilon.Client/Assets/Zilon/Scripts/Commands/QuitTitleRequestCommand.cs
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/SectorUiHandler.cs
Zilon.Client/Assets/Zilon/Scripts/SectorInstaller.cs

#508 #535
Отмена выхода работает корректно. А вот выход в меню не был реализован до конца.

#508 #535 Доработан выход в меню

---

.circleci/config.yml

#596 Улучшение процедуры деплоя

---

Zilon.Client/Assets/Zilon/Scripts/Models/GlobeScene/GlobeWorldVM.cs

#552 Рефакторинг огромного метода GlobeWorldVm

---

Zilon.Core/Zilon.Core.Tests/Tactics/Behaviour/HumanActorTaskSourceTests.cs
Zilon.Core/Zilon.Core/Tactics/Behaviour/HumanActorTaskSource.cs

#232 Рефакторинг тестов на источник команд для персонажа игрока

---

.dependabot/config.yml

Добавлена инструкция для Dependabot

---

Zilon.Client/Assets/Resources/Schemes/Props/Equipments/gold-armor.json
Zilon.Client/Assets/Resources/Schemes/Props/Equipments/gold-helmet.json
Zilon.Client/Assets/Zilon/Prefabs/Sector/BlockIndicator.prefab
Zilon.Client/Assets/Zilon/Prefabs/Sector/DodgeIndicator.prefab
Zilon.Client/Assets/Zilon/Prefabs/Sector/FoundNothingIndicator.prefab
Zilon.Client/Assets/Zilon/Scenes/combat.unity
Zilon.Client/Assets/Zilon/Scripts/Common/PropInfoPopup.cs
Zilon.Client/Assets/Zilon/Scripts/Common/TooltipManager.cs
Zilon.Client/Assets/Zilon/Scripts/Common/UiElementTooltip.cs
Zilon.Client/Assets/Zilon/Scripts/GlobalInstaller.cs
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/CombatLogPanel.cs
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/DamageIndicator.cs
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/MonsterInfoPanel.cs
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/NoBulletHandler.cs
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/NoDamageIndicatorBase.cs
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/SectorNameHandler.cs
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/SectorVM.cs
Zilon.Client/Assets/Zilon/Scripts/Services/HealthHelper.cs
Zilon.Client/Assets/Zilon/Scripts/Services/HealthHelper.cs.meta
Zilon.Client/Assets/Zilon/Scripts/Services/Language.cs
Zilon.Client/Assets/Zilon/Scripts/Services/Language.cs.meta
Zilon.Client/Assets/Zilon/Scripts/Services/LocalizationHelper.cs
Zilon.Client/Assets/Zilon/Scripts/Services/LocalizationHelper.cs.meta
Zilon.Client/Assets/Zilon/Scripts/Services/LogService.cs
Zilon.Client/Assets/Zilon/Scripts/Services/SceneDirector.cs
Zilon.Client/Assets/Zilon/Scripts/Services/StaticPhrases.cs
Zilon.Client/Assets/Zilon/Scripts/Services/StaticPhrases.cs.meta
Zilon.Client/Assets/Zilon/Scripts/Services/UiSettingService.cs
Zilon.Client/Assets/Zilon/Scripts/Services/UiSettingService.cs.meta

Feature 417 russian lang

---

Zilon.Client/Assets/Resources/Schemes/DropTables/champion-loot.json
Zilon.Client/Assets/Resources/Schemes/DropTables/default.json
Zilon.Client/Assets/Resources/Schemes/Locations/intro.json

Ребаланс дропа

---

Zilon.Client/Assets/Zilon/Prefabs/Modals/PersonCreateModalBody.prefab
Zilon.Client/Assets/Zilon/Prefabs/Modals/PersonCreateModalBody.prefab.meta
Zilon.Client/Assets/Zilon/Scenes/combat.unity
Zilon.Client/Assets/Zilon/Scripts/Models/Modals/PersonCreateModalBody.cs
Zilon.Client/Assets/Zilon/Scripts/Models/Modals/PersonCreateModalBody.cs.meta
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/ActorViewModel.cs
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/PlayerPersonInitiator.cs
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/PlayerPersonInitiator.cs.meta
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/SectorUiHandler.cs
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/SectorVM.cs
Zilon.Client/Assets/Zilon/Scripts/Services/CommonModalManagerBase.cs
Zilon.Client/Assets/Zilon/Scripts/Services/StaticPhrases.cs
Zilon.Core/Zilon.Core.Tests/Persons/PerkResolverTests.cs
Zilon.Core/Zilon.Core.sln
Zilon.Core/Zilon.Core/Client/Windows/ICommonModalManager.cs
Zilon.Core/Zilon.Core/Persons/PerkResolver.cs

#420 
Выводит черновой модал с описание текущих перков персонажа.

Модал с предысторией персонажа

---

Zilon.Core/Zilon.Tournament.ApiGate/Launcher/BotInfo.cs
Zilon.Core/Zilon.Tournament.ApiGate/Launcher/BotSettings.cs
Zilon.Core/Zilon.Tournament.ApiGate/Launcher/LauncherService.cs

LGTM не может собрать под c# 8

Откат изменений для c# 8

---

Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/DiseaseEffectViewModel.cs
Zilon.Client/Assets/Zilon/Scripts/Services/DiseaseLocalizationHelper.cs
Zilon.Core/Zilon.Core.Tests/MapGenerators/DiseaseGeneratorTests.cs
Zilon.Core/Zilon.Core/Diseases/Disease.cs
Zilon.Core/Zilon.Core/Diseases/DiseaseName.cs
Zilon.Core/Zilon.Core/Diseases/IDisease.cs
Zilon.Core/Zilon.Core/MapGenerators/DiseaseGenerator.cs
Zilon.Core/Zilon.Core/MapGenerators/DiseaseNames.cs
Zilon.Core/Zilon.Core/MapGenerators/IDiseaseGenerator.cs
Zilon.Core/Zilon.Core/MapGenerators/MonsterGenerator.cs
Zilon.Core/Zilon.Core/Persons/DiseaseData.cs
Zilon.Core/Zilon.Core/Persons/DiseaseProcess.cs
Zilon.Core/Zilon.Core/Persons/IDiseaseData.cs
Zilon.Core/Zilon.Core/Persons/IDiseaseProcess.cs
Zilon.Core/Zilon.Core/Persons/Survival/DiseaseEffect.cs
Zilon.Core/Zilon.Core/Tactics/ISector.cs
Zilon.Core/Zilon.Core/Tactics/Scores.cs
Zilon.Core/Zilon.Core/Tactics/Sector.cs
Zilon.Core/Zilon.Core/Tactics/TacticalActUsageService.cs
Zilon.Core/Zilon.Core/Zilon.Core.csproj

Введен процесс протекания болезни

---

Zilon.Core/Zilon.Core/MapGenerators/DiseaseGenerator.cs
Zilon.Core/Zilon.Core/MapGenerators/MonsterGenerator.cs

Откат тестовых настроек болезней

---

.circleci/config.yml

Revert project key for Sonar

---

Zilon.Client/Assets/Zilon/Scripts/Services/StaticObjectViewModelSelector.cs
Zilon.Core/Zilon.Core/MapGenerators/MapFillerHexNodeOptions.cs
Zilon.Core/Zilon.Core/MapGenerators/StaticObstaclesGenerator.cs
Zilon.Core/Zilon.Core/StaticObjectModules/ILifetimeModule.cs
Zilon.Core/Zilon.Core/StaticObjectModules/IPropDepositModule.cs
Zilon.Core/Zilon.Core/StaticObjectModules/LifetimeModule.cs
Zilon.Core/Zilon.Core/StaticObjectModules/PropDepositModule.cs

Resource gathering p4 - destroy static object then its was exhaused

---

Zilon.Core/Zilon.Core.Tests/StaticObjectModules/DepositDurabilityModuleTests.cs
Zilon.Core/Zilon.Core.Tests/StaticObjectModules/TestCaseDataSources/DepositDurabilityModuleTestCaseDataSource.cs
Zilon.Core/Zilon.Core/StaticObjectModules/DepositDurabilityModule.cs
Zilon.Core/Zilon.Core/StaticObjectModules/DepositLifetimeModule.cs
Zilon.Core/Zilon.Core/StaticObjectModules/IPropDepositModule.cs
Zilon.Core/Zilon.Core/StaticObjectModules/PropDepositModule.cs

Fix resource gathering

---

Zilon.Client/Assets/Zilon/Scripts/DependencyInjection/TaskSourcesExtensions.cs
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/SectorVM.cs

Fix Unity client

---

Zilon.Client/Assets/GameLoopUpdater.cs
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/ActorViewModel.cs
Zilon.Client/Assets/Zilon/Scripts/Services/CommandBlockerService.cs
Zilon.Client/Assets/Zilon/Scripts/Services/ICommandBlockerService.cs
Zilon.Core/Zilon.Core/Tactics/Behaviour/MoveIntention.cs

Fix action speed if monsters faster that player

---

Zilon.Core/Zilon.Core/World/BiomeInitializer.cs
Zilon.Core/Zilon.Core/World/IGlobeExpander.cs

Some refactor during planning milestone.

Split BiomeInitializer.cs and IGlobeExpander.cs to different documents

---

.github/workflows/coverall.yml

Fix coverall build config

---

Zilon.Client/Assets/Zilon/Scenes/combat.unity
Zilon.Client/Assets/Zilon/Scripts/Services/StaticPhrases.cs

Fix button description

---

Zilon.Core/Zilon.Bot.Players.Tests/Triggers/ExploredTriggerTestCaseSource.cs
Zilon.Core/Zilon.Bot.Players.Tests/Triggers/ExploredTriggerTests.cs
Zilon.Core/Zilon.Bot.Players/Triggers/ExploredTrigger.cs
Zilon.Core/Zilon.Core/PersonModules/IPersonExtensions.cs

Add tests for ExploredTrigger

---

Zilon.Client/Assets/Zilon/Scripts/Models/Modals/CloseBehaviourOperation.cs
Zilon.Client/Assets/Zilon/Scripts/Models/Modals/CloseBehaviourOperation.cs.meta
Zilon.Client/Assets/Zilon/Scripts/Models/Modals/ContainerModalBody.cs
Zilon.Client/Assets/Zilon/Scripts/Models/Modals/IModalWindowHandler.cs
Zilon.Client/Assets/Zilon/Scripts/Models/Modals/InstructionModalBody.cs
Zilon.Client/Assets/Zilon/Scripts/Models/Modals/InventoryModalBody.cs
Zilon.Client/Assets/Zilon/Scripts/Models/Modals/ModalDialog.cs
Zilon.Client/Assets/Zilon/Scripts/Models/Modals/PerksModalBody.cs
Zilon.Client/Assets/Zilon/Scripts/Models/Modals/QuitModalBody.cs
Zilon.Client/Assets/Zilon/Scripts/Models/Modals/ScoreModalBody.cs
Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/WinModalBody.cs

Add close behaviour fow modal windows

---

Zilon.Client/Assets/Zilon/Prefabs/Modals/Tutorial/InstructionModalBody.prefab
Zilon.Client/Assets/Zilon/Scripts/Models/Modals/InstructionModalBody.cs

Fix instruction modal buttons

---

Zilon.Client/Assets/Zilon/Scripts/Models/SectorScene/MovePathVisualizer.cs
Zilon.Core/Zilon.Core/Commands/Sector/MoveCommand.cs

Fix path visualizer

---

Zilon.Core/Zilon.Core.Tests/PerkHelperTests.cs
Zilon.Core/Zilon.Core/PerkHelper.cs
Zilon.Core/Zilon.Tournament.ApiGate/Zilon.Tournament.ApiGate.csproj

*Changes*
- Fix PerkHelper.ConvertTotalLevel() from https://dotnetfiddle.net/C3Clbd
- Degrade `CodeGeneration` package from `ApiGate`.
*Checklist*

Fix PerkHelper.cs

---

.github/workflows/mutation-test-stryker.yml
Zilon.Core/Zilon.Core.Tests/PerkHelperTestCaseSource.cs
Zilon.Core/Zilon.Core.Tests/PerkHelperTests.cs
Zilon.Core/Zilon.Core/CubeCoords.cs
Zilon.Core/Zilon.Core/PerkHelper.cs

*Changes*
- Add mutation testing via Stryker
- Add testcases for perk helper
*Checklist*

Feature Stryker mutator

---

Zilon.Client/Assets/Resources/Schemes/Perks/battle-dogmas.json
Zilon.Client/Assets/Zilon/Scripts/Models/Modals/PerkItemViewModel.cs
Zilon.Core/Zilon.Core.Specs/Steps/PerkSteps.cs
Zilon.Core/Zilon.Core.Tests.Common/Schemes/TestPerkScheme.cs
Zilon.Core/Zilon.Core.Tests/PerkHelperTestCaseSource.cs
Zilon.Core/Zilon.Core.Tests/PerkHelperTests.cs
Zilon.Core/Zilon.Core.Tests/PersonModules/EvolutionModuleTests.cs
Zilon.Core/Zilon.Core.Tests/Persons/PerkResolverTests.cs
Zilon.Core/Zilon.Core/CubeCoords.cs
Zilon.Core/Zilon.Core/PerkHelper.cs
Zilon.Core/Zilon.Core/PersonModules/CombatActModule.cs
Zilon.Core/Zilon.Core/PersonModules/CombatStatsModule.cs
Zilon.Core/Zilon.Core/PersonModules/EvolutionModule.cs
Zilon.Core/Zilon.Core/PersonModules/HumanSurvivalModule.cs
Zilon.Core/Zilon.Core/Persons/PerkLevel.cs
Zilon.Core/Zilon.Core/Persons/PerkResolver.cs
Zilon.Core/Zilon.Core/Schemes/PerkLevelSubScheme.cs

*Changes*
- Fix methods to get next level, check level cap.
- Fix tests, specs.
*Checklist*

Fix perk helper

---

Zilon.Client/Assets/Zilon/Scripts/Models/Modals/PerkItemViewModel.cs
Zilon.Core/Zilon.Core.Tests/PerkHelperTestCaseSource.cs
Zilon.Core/Zilon.Core.Tests/PerkHelperTests.cs
Zilon.Core/Zilon.Core/PerkHelper.cs

*Changes*
- Add tests
*Checklist*

Add test to PerkHelper.ConvertLevelSubsToTotal

---

.github/workflows/linter.yml

*Changes*
- Update dotnet-format
- Update R#
*Checklist*

Update versions of linters

---

Zilon.Client/Assets/Resources/Schemes/Monsters/hell-rock.json
Zilon.Client/Assets/Resources/Schemes/Monsters/rat-king.json
Zilon.Client/Assets/Resources/Schemes/Monsters/rat-mutant.json
Zilon.Core/Zilon.Core.Tests.Common/Schemes/TestMonsterScheme.cs
Zilon.Core/Zilon.Core.Tests/PersonModules/MonsterMovingModuleTestCaseSource.cs
Zilon.Core/Zilon.Core.Tests/PersonModules/MonsterMovingModuleTests.cs
Zilon.Core/Zilon.Core/PersonModules/MonsterMovingModule.cs
Zilon.Core/Zilon.Core/Schemes/IMonsterScheme.cs
Zilon.Core/Zilon.Core/Schemes/MonsterScheme.cs
Zilon.Core/Zilon.Core/World/GlobeMetrics.cs

Continues #906
*Changes*
- Replace monster base speed with move speed factor.
- Slow down rat king, rat mutant and hell rock.
*Checklist*

Feature monster move factor

---

Zilon.Client/Assets/Resources/Schemes/PersonTemplates/undertaker.json

Continues #907
*Changes*
- Add shovel to undertaker template.
*Checklist*

Add shovel for undertaker

---

Zilon.Client/Assets/Resources/Schemes/Props/Equipments/club.json
Zilon.Core/Zilon.Core.Tests/Persons/AttackActorJobProgressTestCaseSource.cs
Zilon.Core/Zilon.Core.Tests/Persons/AttackActorJobProgressTests.cs
Zilon.Core/Zilon.Core/Common/PropTags.cs
Zilon.Core/Zilon.Core/Persons/AttackActorJobProgress.cs
Zilon.Core/Zilon.Core/Props/Equipment.cs

*Changes*
Resolves #1045
- Add tests for AttackJobProgress
- Fix progress applying
*Checklist*

Fix 1045 weapon progress applying

---

Zilon.Client/Assets/Zilon/Scripts/Services/StaticPhrases.cs

Fixes #1044 
*Changes*
- Add static phrase for tool, pick axe and shovel tags.
*Checklist*

Fix weapon tool localized strings

---

.github/workflows/build-unity-client.yml
Zilon.Client/Assets/AddressableAssetsData/AddressableAssetSettings.asset
Zilon.Client/Assets/AddressableAssetsData/Windows.meta
Zilon.Client/Assets/Resources/Icons/props/stone.png.meta

Resolves #997 
*Changes*
- Done things as suggested in https://forum.unity.com/threads/localization-dont-work-in-windows64-build.1075873/
*Checklist*

Localization recreate 3

---

.github/workflows/mutation-test-stryker.yml
Zilon.Core/Zilon.Core/Diseases/DiseaseName.cs
Zilon.Core/Zilon.Core/MapGenerators/MapFillerHexNodeOptions.cs
Zilon.Core/Zilon.Core/OffsetCoords.cs
Zilon.Core/Zilon.Core/Tactics/Spatial/HexMap.cs
Zilon.Core/Zilon.Core/World/GlobeMetrics.cs
Zilon.Core/Zilon.Core/World/GlobeTransitionHandler.cs

*Changes*
- Add coverage ignoring for GetHashCode and Equals to clean up mutation report
*Checklist*

Fix stryker mutator ignore methods

---

.github/workflows/coverage-report-generator.yml
Zilon.Core/Zilon.Core/Common/HexHelper.cs
Zilon.Core/Zilon.Core/Common/MathUtils.cs

*Changes*
Improve #1082 solution.
- Change AxialCoords to store `int` instead `float`
*Checklist*

Refactor convert

---

.github/pull_request_template.md
Zilon.Core/Zilon.Core/Commands/Sector/SectorTransitionMoveCommand.cs
Zilon.Core/Zilon.Core/World/TransitionPool.cs

Fix transition command

---

Zilon.Core/CDT.LAST.MonoGameClient/Screens/GlobeSelectionScreen.cs

*Changes*
- Remove await for command loop start that was added #1122.
*Checklist*

Fix globe selection

---

Zilon.Core/CDT.LAST.MonoGameClient/ViewModels/MainScene/CommandInput.cs
Zilon.Core/Zilon.Core.Tests/Client/Sector/CommandLoopUpdaterTests.cs

*Changes*
- Fix usage of TCS in tests as said in recomendations.
*Checklist*

Fix usage of TCS in tests

---

.github/workflows/build-client.yml
.github/workflows/mutation-test-stryker.yml
Zilon.Core/CDT.LAST.MonoGameClient/CDT.LAST.MonoGameClient.csproj
Zilon.Core/Zilon.Bot.Players.DevelopmentTests/Zilon.Bot.Players.DevelopmentTests.csproj
Zilon.Core/Zilon.Bot.Players.NetCore/Zilon.Bot.Players.NetCore.csproj
Zilon.Core/Zilon.Bot.Players.Tests/Zilon.Bot.Players.Tests.csproj
Zilon.Core/Zilon.Bot.Players/Zilon.Bot.Players.csproj
Zilon.Core/Zilon.Bot.Sdk/Zilon.Bot.Sdk.csproj
Zilon.Core/Zilon.BotEnvironment/Zilon.BotEnvironment.csproj
Zilon.Core/Zilon.BotMassLauncher/Zilon.BotMassLauncher.csproj
Zilon.Core/Zilon.CommonUtilities/Zilon.CommonUtilities.csproj
Zilon.Core/Zilon.Core.Benchmarks.Common/Zilon.Core.Benchmarks.Common.csproj
Zilon.Core/Zilon.Core.Benchmarks.CreateSector/Zilon.Core.Benchmarks.CreateSector.csproj
Zilon.Core/Zilon.Core.Benchmarks.Gameplay/Zilon.Core.Benchmarks.Gameplay.csproj
Zilon.Core/Zilon.Core.Benckmarks.Fow/Zilon.Core.Benchmarks.Fow.csproj
Zilon.Core/Zilon.Core.DiTests/Zilon.Core.DiTests.csproj
Zilon.Core/Zilon.Core.MassSectorGenerator/Zilon.Core.MassSectorGenerator.csproj
Zilon.Core/Zilon.Core.Specs/Zilon.Core.Specs.csproj
Zilon.Core/Zilon.Core.Tests.Common/Zilon.Core.Tests.Common.csproj
Zilon.Core/Zilon.Core.Tests/Zilon.Core.Tests.csproj
Zilon.Core/Zilon.Core/Zilon.Core.csproj
Zilon.Core/Zilon.DependencyInjection/Zilon.DependencyInjection.csproj
Zilon.Core/Zilon.Emulation.Common/Zilon.Emulation.Common.csproj
Zilon.Core/Zilon.GlobeObserver/Zilon.GlobeObserver.csproj
Zilon.Core/Zilon.TextClient/Zilon.TextClient.csproj
Zilon.Core/Zilon.Tournament.ApiGate/Zilon.Tournament.ApiGate.csproj

*Changes*
- Fix mutation testing.
- Up version of the Stryker Mutator library.
- Fix target frameworks from `net5` to `net5.0`.
- Up version of SDK in client building workflow.
*Checklist*

Fix mutation testing

---

Zilon.Core/CDT.LAST.MonoGameClient/Engine/FpsCounter.cs
Zilon.Core/CDT.LAST.MonoGameClient/LivGame.cs

*Changes*
- Add FpsCounter component.
*Checklist*

Add FpsCounter

---

.github/workflows/bot-tests.yml

Remove unused branch from workflow

---

Zilon.Core/CDT.LAST.MonoGameClient/ViewModels/MainScene/ActorMoveEngine.cs
Zilon.Core/CDT.LAST.MonoGameClient/ViewModels/MainScene/ActorSectorTransitionMoveEngine.cs

*Changes*
- Added checks of sound disposed state before playing.
*Checklist*

Fix playing of disposed

---

Zilon.Client/Assets/Resources/Schemes/Locations/intro.json
Zilon.Core/Zilon.Core.Tests/MapGenerators/CellularAutomatonStyle/InteriorObjectRandomSourceTests.cs
Zilon.Core/Zilon.Core.Tests/MapGenerators/SectorProceduralGeneratorTests.cs
Zilon.Core/Zilon.Core/MapGenerators/CellularAutomatonStyle/InteriorObjectRandomSource.cs
Zilon.Core/Zilon.Core/MapGenerators/IStaticObjectsGenerator.cs
Zilon.Core/Zilon.Core/MapGenerators/SectorGenerator.cs
Zilon.Core/Zilon.Core/MapGenerators/StaticObjectGenerator.cs
Zilon.Core/Zilon.Core/MapGenerators/StaticObjectsGeneratorRandomSource.cs
Zilon.Core/Zilon.Core/World/ResourceMaterializationMap.cs
Zilon.Core/Zilon.Emulation.Common/InitializationBase.cs

*Changes*
- Only brushes are being generated in intro location.
- Dramatically reduce monster count in intro locations.
- Rename `IStaticObstaclesGenerator` into `IStaticObjectGenerator`.
*Checklist*

Brushes resources

---

.github/workflows/codeql-analysis.yml

Use specified build command

---

.github/workflows/sonar-cloud.yml

Continues #1226 
*Changes*
- ...
*Checklist*

Fix branch excluding

---

.github/workflows/sonar-cloud.yml

Continues #1226 
*Changes*
- ...
*Checklist*

Fix branches excluding
